"""
Lyra Research - Deep Research Agent

Multi-source research discovery, analysis, and synthesis.
"""

from lyra_research.discovery import (
    ArXivDiscovery,
    GitHubDiscovery,
    MultiSourceDiscovery,
    ResearchSource,
    SemanticScholarDiscovery,
    SourceType,
)
from lyra_research.fetchers import ContentFetcher, ParsedContent, PDFExtractor, READMEParser, WebScraper
from lyra_research.analysis import (
    PaperAnalysis,
    PaperAnalyzer,
    QualityScore,
    QualityScorer,
    RepositoryAnalysis,
    RepositoryAnalyzer,
)
from lyra_research.synthesis import (
    CitationNetworkBuilder,
    Concept,
    ConceptExtractor,
    KnowledgeEdge,
    KnowledgeGraph,
    KnowledgeNode,
    Relationship,
    RelationshipDiscovery,
)
from lyra_research.strategies import (
    QueryExpander,
    RankedResult,
    ResearchPlanner,
    ResultFilter,
    ResultRanker,
    SearchPlan,
    SearchStrategy,
    StoppingCriteria,
)
from lyra_research.sources import (
    ACLAnthologyDiscovery,
    CitationTraversal,
    GitHubActivityScorer,
    HuggingFacePapersDiscovery,
    OpenReviewDiscovery,
    PapersWithCodeDiscovery,
    SourceQualityScorer,
)
from lyra_research.memory import (
    CorpusEntry,
    LocalCorpus,
    ResearchCase,
    ResearchNote,
    ResearchNoteStore,
    ResearchStrategy,
    ResearchStrategyMemory,
    SessionCaseBank,
)
from lyra_research.intelligence import (
    AuditReport,
    ChecklistItem,
    ClaimEvidence,
    Contradiction,
    ContradictionDetector,
    EvidenceAudit,
    FalsificationChecker,
    FalsificationNote,
    GapAnalyzer,
    ResearchChecklist,
    ResearchGap,
    VerifiableChecklistGenerator,
)

__version__ = "0.1.0"

__all__ = [
    "ArXivDiscovery",
    "GitHubDiscovery",
    "SemanticScholarDiscovery",
    "MultiSourceDiscovery",
    "ResearchSource",
    "SourceType",
    "ContentFetcher",
    "ParsedContent",
    "PDFExtractor",
    "READMEParser",
    "WebScraper",
    "PaperAnalysis",
    "PaperAnalyzer",
    "RepositoryAnalysis",
    "RepositoryAnalyzer",
    "QualityScore",
    "QualityScorer",
    "CitationNetworkBuilder",
    "Concept",
    "ConceptExtractor",
    "KnowledgeGraph",
    "KnowledgeNode",
    "KnowledgeEdge",
    "Relationship",
    "RelationshipDiscovery",
    "QueryExpander",
    "ResultFilter",
    "ResultRanker",
    "RankedResult",
    "ResearchPlanner",
    "SearchPlan",
    "SearchStrategy",
    "StoppingCriteria",
    "ACLAnthologyDiscovery",
    "CitationTraversal",
    "GitHubActivityScorer",
    "HuggingFacePapersDiscovery",
    "OpenReviewDiscovery",
    "PapersWithCodeDiscovery",
    "SourceQualityScorer",
    "VerifiableChecklistGenerator",
    "ResearchChecklist",
    "ChecklistItem",
    "EvidenceAudit",
    "AuditReport",
    "ClaimEvidence",
    "ContradictionDetector",
    "Contradiction",
    "GapAnalyzer",
    "ResearchGap",
    "FalsificationChecker",
    "FalsificationNote",
    "ResearchNote",
    "ResearchNoteStore",
    "CorpusEntry",
    "LocalCorpus",
    "ResearchStrategy",
    "ResearchStrategyMemory",
    "ResearchCase",
    "SessionCaseBank",
]
