"""
Lyra Research - Deep Research Agent

Multi-source research discovery, analysis, and synthesis.
"""

from lyra_research.adversarial_reviewer import (
    AdversarialReviewer,
    Claim,
    DisagreementResolution,
    ReviewerContextBudget,
    ReviewIssue,
    ReviewResult,
)
from lyra_research.analysis import (
    PaperAnalysis,
    PaperAnalyzer,
    QualityScore,
    QualityScorer,
    RepositoryAnalysis,
    RepositoryAnalyzer,
)
from lyra_research.coordination import (
    CircuitBreaker,
    CircuitBreakerStats,
    CoordinationManager,
    FailureType,
    HealthChecker,
    HealthMetrics,
    RetryPolicy,
    Task,
    TaskState,
    TimeoutEnforcer,
)
from lyra_research.discovery import (
    ArXivDiscovery,
    GitHubDiscovery,
    MultiSourceDiscovery,
    ResearchSource,
    SemanticScholarDiscovery,
    SourceType,
)
from lyra_research.evaluation import (
    QualityTrendTracker,
    ResearchQualityEvaluator,
    ResearchQualityMetrics,
    SelfEvaluationAgent,
)
from lyra_research.fetchers import (
    ContentFetcher,
    ParsedContent,
    PDFExtractor,
    READMEParser,
    WebScraper,
)
from lyra_research.intelligence import (
    AuditReport,
    ChecklistItem,
    ClaimEvidence,
    Contradiction,
    ContradictionDetector,
    EvidenceAudit,
    FalsificationChecker,
    FalsificationNote,
    GapAnalyzer,
    ResearchChecklist,
    ResearchGap,
    VerifiableChecklistGenerator,
)
from lyra_research.learning import (
    CaseMatch,
    CaseSelectionPolicy,
    DomainExpertiseAccumulator,
    DomainModel,
    ExtractedStrategy,
    GateDecision,
    ResearchStrategyExtractor,
    ResearchWorkflowOptimizer,
    SelfImprovementGate,
    WorkflowInsight,
)
from lyra_research.memory import (
    CorpusEntry,
    LocalCorpus,
    ResearchCase,
    ResearchNote,
    ResearchNoteStore,
    ResearchStrategy,
    ResearchStrategyMemory,
    SessionCaseBank,
)
from lyra_research.orchestrator import ResearchOrchestrator, ResearchProgress
from lyra_research.reporter import (
    BoundCitation,
    CitationBinder,
    CrossSourceSynthesizer,
    FieldTaxonomy,
    QualityReport,
    ReportQualityChecker,
    ResearchReport,
    ResearchReportGenerator,
    SynthesisResult,
)
from lyra_research.sibyl_harness import (
    ExperimentStatus,
    ExperimentTrial,
    SibylPipeline,
    TrialConfig,
    TrialFailure,
    TrialHarness,
)
from lyra_research.skills import (
    QueryRefinementSkill,
    RefinementSuggestion,
    ResearchSkill,
    ResearchSkillStore,
    SkillEvolutionRecord,
    SkillEvolutionTracker,
    StrategyAdaptationSkill,
)
from lyra_research.sources import (
    ACLAnthologyDiscovery,
    CitationTraversal,
    GitHubActivityScorer,
    HuggingFacePapersDiscovery,
    OpenReviewDiscovery,
    PapersWithCodeDiscovery,
    SourceQualityScorer,
)
from lyra_research.strategies import (
    QueryExpander,
    RankedResult,
    ResearchPlanner,
    ResultFilter,
    ResultRanker,
    SearchPlan,
    SearchStrategy,
    StoppingCriteria,
)
from lyra_research.synthesis import (
    CitationNetworkBuilder,
    Concept,
    ConceptExtractor,
    KnowledgeEdge,
    KnowledgeGraph,
    KnowledgeNode,
    Relationship,
    RelationshipDiscovery,
)

# Zero-Index Retrieval — direct corpus search without pre-built indexes
from lyra_research.zero_index import (
    ContextLevel,
    CorpusStats,
    SearchResult,
    ZeroIndexConfig,
    ZeroIndexRetriever,
)

# Phase 21 Architecture Upgrades
from lyra_research.research_daemon import (
    DaemonConfig,
    ResearchDaemon,
)
from lyra_research.research_notebook import (
    NotebookEntry,
    ResearchNotebook,
)
from lyra_research.research_state import (
    ResearchPhase,
    SessionStatus,
    UnifiedResearchState,
)

__version__ = "0.2.0"

__all__ = [
    "ResearchOrchestrator",
    "ResearchProgress",
    "ArXivDiscovery",
    "GitHubDiscovery",
    "SemanticScholarDiscovery",
    "MultiSourceDiscovery",
    "ResearchSource",
    "SourceType",
    "ContentFetcher",
    "ParsedContent",
    "PDFExtractor",
    "READMEParser",
    "WebScraper",
    "PaperAnalysis",
    "PaperAnalyzer",
    "RepositoryAnalysis",
    "RepositoryAnalyzer",
    "QualityScore",
    "QualityScorer",
    "CitationNetworkBuilder",
    "Concept",
    "ConceptExtractor",
    "KnowledgeGraph",
    "KnowledgeNode",
    "KnowledgeEdge",
    "Relationship",
    "RelationshipDiscovery",
    "QueryExpander",
    "ResultFilter",
    "ResultRanker",
    "RankedResult",
    "ResearchPlanner",
    "SearchPlan",
    "SearchStrategy",
    "StoppingCriteria",
    "ACLAnthologyDiscovery",
    "CitationTraversal",
    "GitHubActivityScorer",
    "HuggingFacePapersDiscovery",
    "OpenReviewDiscovery",
    "PapersWithCodeDiscovery",
    "SourceQualityScorer",
    "BoundCitation",
    "CitationBinder",
    "CrossSourceSynthesizer",
    "FieldTaxonomy",
    "QualityReport",
    "ReportQualityChecker",
    "ResearchReport",
    "ResearchReportGenerator",
    "SynthesisResult",
    "VerifiableChecklistGenerator",
    "ResearchChecklist",
    "ChecklistItem",
    "EvidenceAudit",
    "AuditReport",
    "ClaimEvidence",
    "ContradictionDetector",
    "Contradiction",
    "GapAnalyzer",
    "ResearchGap",
    "FalsificationChecker",
    "FalsificationNote",
    "AdversarialReviewer",
    "Claim",
    "DisagreementResolution",
    "ReviewerContextBudget",
    "ReviewIssue",
    "ReviewResult",
    "ResearchNote",
    "ResearchNoteStore",
    "CorpusEntry",
    "LocalCorpus",
    "ResearchStrategy",
    "ResearchStrategyMemory",
    "ResearchCase",
    "SessionCaseBank",
    "ResearchSkill",
    "ResearchSkillStore",
    "RefinementSuggestion",
    "QueryRefinementSkill",
    "StrategyAdaptationSkill",
    "SkillEvolutionRecord",
    "SkillEvolutionTracker",
    "ResearchQualityMetrics",
    "ResearchQualityEvaluator",
    "QualityTrendTracker",
    "SelfEvaluationAgent",
    "ExtractedStrategy",
    "ResearchStrategyExtractor",
    "CaseMatch",
    "CaseSelectionPolicy",
    "DomainModel",
    "DomainExpertiseAccumulator",
    "WorkflowInsight",
    "ResearchWorkflowOptimizer",
    "GateDecision",
    "SelfImprovementGate",
    "CircuitBreaker",
    "CircuitBreakerStats",
    "CoordinationManager",
    "FailureType",
    "HealthChecker",
    "HealthMetrics",
    "RetryPolicy",
    "Task",
    "TaskState",
    "TimeoutEnforcer",
    # Sibyl-style trial harnesses
    "TrialHarness",
    "TrialConfig",
    "ExperimentTrial",
    "TrialFailure",
    "ExperimentStatus",
    "SibylPipeline",
    # Zero-Index Retrieval
    "ContextLevel",
    "SearchResult",
    "ZeroIndexConfig",
    "ZeroIndexRetriever",
    "CorpusStats",
    # Phase 21 Architecture Upgrades
    "DaemonConfig",
    "NotebookEntry",
    "ResearchDaemon",
    "ResearchNotebook",
    "ResearchPhase",
    "SessionStatus",
    "UnifiedResearchState",
]
