"""Heuristic Prompt Compressor — Phase F (LLMLingua/Selective Context inspired).

Zero-dependency compression of injected context before API calls.
Removes boilerplate, collapses blank runs, truncates long URLs.
Achieves ~20-40% reduction on typical injected content.

Evidence:
- LLMLingua (EMNLP'23, arXiv:2310.05736): 20x with proxy LLM
- Selective Context (EMNLP'23, arXiv:2310.06201): 40% via self-information
- This impl: heuristic-only, zero cost, ~20-40% on real content
"""

from __future__ import annotations

import re
from typing import ClassVar


class HeuristicCompressor:
    """Compresses text via textual heuristics. Zero external dependencies."""

    _BLANK_RUN: ClassVar[re.Pattern] = re.compile(r'\n{3,}')
    _TRAILING_WS: ClassVar[re.Pattern] = re.compile(r'[ \t]+$', re.MULTILINE)
    _COPYRIGHT: ClassVar[re.Pattern] = re.compile(
        r'^[#/*\s]*(Copyright|License|Author|Generated by|Auto-generated|DO NOT EDIT'
        r'|This file is auto|Automatically generated).*$',
        re.MULTILINE | re.IGNORECASE,
    )
    _JAVADOC_PARAM: ClassVar[re.Pattern] = re.compile(
        r'^\s*\*\s*@(param|returns?|throws?|deprecated|see|since|version|author)\b.*$',
        re.MULTILINE,
    )
    _LONG_URL: ClassVar[re.Pattern] = re.compile(r'https?://\S{80,}')
    _REPEATED_DASHES: ClassVar[re.Pattern] = re.compile(r'[-=*_]{20,}')

    MIN_LENGTH_TO_COMPRESS: ClassVar[int] = 400
    MIN_RATIO: ClassVar[float] = 0.45  # never reduce below 45% of original

    def compress(self, text: str) -> str:
        """Compress text. Returns original if too short or over-compressed."""
        if not text or len(text) < self.MIN_LENGTH_TO_COMPRESS:
            return text

        result = self._BLANK_RUN.sub('\n\n', text)
        result = self._TRAILING_WS.sub('', result)
        result = self._COPYRIGHT.sub('', result)
        result = self._JAVADOC_PARAM.sub('', result)
        result = self._LONG_URL.sub('[url]', result)
        result = self._REPEATED_DASHES.sub('---', result)
        result = self._BLANK_RUN.sub('\n\n', result).strip()

        # Safety: never compress too aggressively
        if len(text) > 0 and len(result) / len(text) < self.MIN_RATIO:
            return text
        return result

    def compress_messages(self, messages: list[dict], skip_last: int = 2) -> list[dict]:
        """Compress content of all messages except the last skip_last ones.

        Never touches the most recent turns — the model needs exact recent state.
        Returns a new list (does not mutate the input).
        """
        cutoff = max(0, len(messages) - skip_last)
        result: list[dict] = []
        for i, msg in enumerate(messages):
            if i >= cutoff:
                result.append(msg)
            else:
                content = msg.get("content", "")
                compressed = self.compress(content) if isinstance(content, str) else content
                result.append({**msg, "content": compressed})
        return result

    def ratio(self, original: str, compressed: str) -> float:
        return len(compressed) / max(len(original), 1)
