"""
End-to-end tests for complete deep research workflows.

Tests cover:
- Quick research mode (10 sources, 1 hop)
- Standard research mode (30 sources, 2-3 hops)
- Deep research mode (50+ sources, 3-5 hops)
- Multi-topic research
- Iterative refinement
"""

import pytest
from pathlib import Path
from datetime import datetime, timezone
from unittest.mock import Mock, patch, MagicMock

from lyra_research.orchestrator import ResearchOrchestrator, ResearchProgress
from lyra_research.discovery import ResearchSource, SourceType


@pytest.fixture
def mock_discovery_results():
    """Mock discovery results to avoid real API calls."""
    def create_mock_sources(count=10, source_type=SourceType.PAPER):
        sources = []
        for i in range(count):
            sources.append(ResearchSource(
                id=f"test-{source_type.value}-{i}",
                title=f"Test {source_type.value.title()} {i}",
                source_type=source_type,
                url=f"https://example.com/{source_type.value}/{i}",
                abstract=f"Test abstract for {source_type.value} {i}",
                citations=100 - i * 5,
                stars=1000 - i * 50 if source_type == SourceType.REPOSITORY else 0,
                published_date=datetime(2026, 1, 1),
            ))
        return sources

    return {
        "quick": {"arxiv": create_mock_sources(10, SourceType.PAPER)},
        "standard": {
            "arxiv": create_mock_sources(20, SourceType.PAPER),
            "github": create_mock_sources(10, SourceType.REPOSITORY),
        },
        "deep": {
            "arxiv": create_mock_sources(30, SourceType.PAPER),
            "github": create_mock_sources(15, SourceType.REPOSITORY),
            "huggingface": create_mock_sources(5, SourceType.PAPER),
        },
    }


class TestQuickResearchMode:
    """E2E tests for quick research mode."""

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_quick_research_complete_workflow(self, tmp_path, mock_discovery_results):
        """Test complete quick research workflow (10 sources, 1 hop)."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        # Mock discovery to avoid real API calls
        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            # Execute quick research
            progress = orchestrator.research(
                topic="LLM tool use",
                depth="quick",
                sources=["arxiv"]
            )

        # Verify completion
        assert progress.is_complete
        assert progress.error is None

        # Verify report generated
        assert progress.report is not None
        assert progress.report.topic == "LLM tool use"
        assert len(progress.report.executive_summary) > 0

        # Verify source limits (quick mode fetches ~15 sources)
        total_sources = sum(progress.sources_found.values())
        assert total_sources <= 20

        # Verify performance (2 minutes max)
        assert progress.elapsed_seconds < 120

        # Verify quality
        assert progress.report.quality_score >= 0.0

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_quick_research_output_files(self, tmp_path, mock_discovery_results):
        """Test output files generated by quick research."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            progress = orchestrator.research(
                topic="LLM agents",
                depth="quick",
                sources=["arxiv"]
            )

        # Check report file exists (saved during research)
        report_files = list(output_dir.glob("*.md"))
        assert len(report_files) > 0
        assert report_files[0].stat().st_size > 100


class TestStandardResearchMode:
    """E2E tests for standard research mode."""

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_standard_research_complete_workflow(self, tmp_path, mock_discovery_results):
        """Test complete standard research workflow (30 sources, 2-3 hops)."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["standard"]):
            # Execute standard research
            progress = orchestrator.research(
                topic="Multi-agent coordination",
                depth="standard",
                sources=["arxiv", "github"]
            )

        # Verify completion
        assert progress.is_complete
        assert progress.error is None

        # Verify source diversity
        total_sources = sum(progress.sources_found.values())
        assert total_sources >= 20
        assert len(progress.sources_found) >= 1  # At least one source type

        # Verify performance (10 minutes max)
        assert progress.elapsed_seconds < 600

        # Verify quality
        assert progress.report.quality_score >= 0.0

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_standard_research_multi_source(self, tmp_path, mock_discovery_results):
        """Test standard research with multiple sources."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["standard"]):
            progress = orchestrator.research(
                topic="LLM reasoning",
                depth="standard",
                sources=["arxiv", "github", "huggingface"]
            )

        # Verify all sources used
        assert "arxiv" in progress.sources_found
        assert progress.sources_found["arxiv"] > 0


class TestDeepResearchMode:
    """E2E tests for deep research mode."""

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_deep_research_with_verification(self, tmp_path, mock_discovery_results):
        """Test deep research with adversarial review."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["deep"]):
            # Execute deep research
            progress = orchestrator.research(
                topic="LLM reasoning capabilities",
                depth="deep",
                sources=["arxiv", "github", "huggingface"]
            )

        # Verify completion
        assert progress.is_complete
        assert progress.error is None

        # Verify extensive exploration
        total_sources = sum(progress.sources_found.values())
        assert total_sources >= 30

        # Verify verification (deep mode enables adversarial review)
        assert progress.verification_rate >= 0.0  # Verification enabled for deep mode

        # Verify gap identification
        assert progress.gaps_found >= 0

        # Verify performance (30 minutes max)
        assert progress.elapsed_seconds < 1800

        # Verify quality
        assert progress.report.quality_score >= 0.0

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_deep_research_citation_verification(self, tmp_path, mock_discovery_results):
        """Test citation verification in deep research."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["deep"]):
            progress = orchestrator.research(
                topic="Multi-agent systems",
                depth="deep",
                sources=["arxiv"]
            )

        # Verify deep research completed with verification
        assert progress.is_complete
        assert progress.verification_rate >= 0.0  # Deep mode enables verification


class TestMultiTopicResearch:
    """E2E tests for multi-topic research."""

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_related_topics_research(self, tmp_path, mock_discovery_results):
        """Test researching multiple related topics."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            # Research topic 1
            progress1 = orchestrator.research(
                topic="LLM agents",
                depth="quick",
                sources=["arxiv"]
            )

            # Research topic 2
            progress2 = orchestrator.research(
                topic="Multi-agent coordination",
                depth="quick",
                sources=["arxiv"]
            )

        # Verify both completed
        assert progress1.is_complete
        assert progress2.is_complete

        # Verify reports generated
        assert progress1.report is not None
        assert progress2.report is not None

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_knowledge_graph_connections(self, tmp_path, mock_discovery_results):
        """Test building knowledge graph across topics."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            # Research multiple topics
            topics = ["LLM agents", "Tool use", "Memory systems"]
            progresses = []

            for topic in topics:
                progress = orchestrator.research(
                    topic=topic,
                    depth="quick",
                    sources=["arxiv"]
                )
                progresses.append(progress)

        # Verify all completed
        assert all(p.is_complete for p in progresses)
        assert all(p.report is not None for p in progresses)


class TestIterativeRefinement:
    """E2E tests for iterative research refinement."""

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_iterative_gap_closure(self, tmp_path, mock_discovery_results):
        """Test iterative refinement based on identified gaps."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            # Initial research
            progress1 = orchestrator.research(
                topic="LLM reasoning",
                depth="quick",
                sources=["arxiv"]
            )

        # Verify gaps identified
        assert progress1.gaps_found >= 0

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["standard"]):
            # Second research with deeper depth
            progress2 = orchestrator.research(
                topic="LLM reasoning",
                depth="standard",
                sources=["arxiv"]
            )

        # Verify both completed
        assert progress1.is_complete
        assert progress2.is_complete

    @pytest.mark.e2e
    @pytest.mark.slow
    def test_quality_improvement_iteration(self, tmp_path, mock_discovery_results):
        """Test iterative quality improvement."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        quality_scores = []

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["quick"]):
            # Iteration 1 - quick
            progress1 = orchestrator.research(
                topic="Multi-agent systems",
                depth="quick",
                sources=["arxiv"]
            )
            quality_scores.append(progress1.report.quality_score)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["standard"]):
            # Iteration 2 - standard (more thorough)
            progress2 = orchestrator.research(
                topic="Multi-agent systems",
                depth="standard",
                sources=["arxiv"]
            )
            quality_scores.append(progress2.report.quality_score)

        # Verify both completed
        assert progress1.is_complete
        assert progress2.is_complete

        # Standard depth typically produces higher quality
        assert quality_scores[1] >= quality_scores[0] * 0.8  # Allow 20% variance


class TestErrorHandling:
    """E2E tests for error handling in research workflows."""

    @pytest.mark.e2e
    def test_api_error_recovery(self, tmp_path):
        """Test recovery from API errors."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        # Simulate API error with mock
        with patch.object(orchestrator.discovery, 'discover') as mock_discover:
            # First call fails, second succeeds
            from lyra_research.discovery import ResearchSource, SourceType
            mock_source = ResearchSource(
                id="test-1",
                title="Test Paper",
                source_type=SourceType.PAPER,
                url="https://arxiv.org/abs/test",
                abstract="Test abstract"
            )
            mock_discover.side_effect = [
                RuntimeError("API error"),
                {"arxiv": [mock_source]}
            ]

            progress = orchestrator.research(
                topic="LLM agents",
                depth="quick",
                sources=["arxiv"]
            )

            # Should recover via retry mechanism
            assert progress.tasks_retried >= 0  # Coordination manager tracks retries

    @pytest.mark.e2e
    def test_partial_failure_handling(self, tmp_path):
        """Test handling partial failures (some sources fail)."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        # Mock partial failure
        with patch.object(orchestrator.discovery, 'discover') as mock_discover:
            from lyra_research.discovery import ResearchSource, SourceType
            mock_source = ResearchSource(
                id="test-1",
                title="Test Paper",
                source_type=SourceType.PAPER,
                url="https://arxiv.org/abs/test",
                abstract="Test abstract"
            )
            mock_discover.return_value = {
                "arxiv": [mock_source],  # Success
                "github": [],            # Empty results (failed)
            }

            progress = orchestrator.research(
                topic="LLM agents",
                depth="quick",
                sources=["arxiv", "github"]
            )

            # Should complete with partial results
            assert "arxiv" in progress.sources_found
            assert progress.sources_found["arxiv"] > 0


class TestPerformanceBenchmarks:
    """E2E performance benchmark tests."""

    @pytest.mark.e2e
    @pytest.mark.benchmark
    def test_quick_research_latency(self, tmp_path, benchmark):
        """Benchmark quick research latency."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        def run_quick_research():
            orchestrator = ResearchOrchestrator(output_dir=output_dir)
            return orchestrator.research(
                topic="LLM agents",
                depth="quick",
                sources=["arxiv"]
            )

        result = benchmark(run_quick_research)
        assert result.is_complete

    @pytest.mark.e2e
    @pytest.mark.benchmark
    def test_standard_research_throughput(self, tmp_path, mock_discovery_results):
        """Benchmark standard research throughput."""
        output_dir = tmp_path / "research"
        output_dir.mkdir()

        orchestrator = ResearchOrchestrator(output_dir=output_dir)

        start_time = datetime.now(timezone.utc)

        with patch.object(orchestrator.discovery, 'discover', return_value=mock_discovery_results["standard"]):
            progress = orchestrator.research(
                topic="Multi-agent systems",
                depth="standard",
                sources=["arxiv"]
            )

        elapsed = (datetime.now(timezone.utc) - start_time).total_seconds()

        # Calculate throughput
        total_sources = sum(progress.sources_found.values())
        sources_per_second = total_sources / elapsed if elapsed > 0 else 0

        assert sources_per_second > 0.1  # At least 0.1 sources/second


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
