"""Persist Lyra settings to ``~/.lyra/settings.json``.

Settings are user preferences: last model, fallback chain, theme,
permission mode, and task auto-detection. This is separate from
``auth.json`` which holds secrets. Both live in ``~/.lyra/`` with
mode-0600 enforced.
"""

from __future__ import annotations

import json
import os
import stat
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "DEFAULT_FALLBACK_CHAIN",
    "LYRA_CONFIG_VERSION",
    "SettingsConfig",
    "load_settings",
    "load_settings_dict",
    "save_settings",
    "settings_path",
    "write_env_file",
]

DEFAULT_FALLBACK_CHAIN = [
    "anthropic", "deepseek", "gemini", "openai",
    "bedrock", "kimi", "qwen", "ollama",
]

LYRA_CONFIG_VERSION = 3

_DEFAULT_HOME_DIRNAME = ".lyra"
_SETTINGS_FILENAME = "settings.json"

_ENV_TEMPLATE = """\
# Lyra environment — generated by {generator}.
# This file is safe to source in your shell profile.
{entries}
"""


def write_env_file(env_path: Path, entries: dict[str, str]) -> None:
    """Write a shell-compatible env file to ``env_path``.

    ``entries`` is a dict of key/value pairs; each is written as
    ``export KEY='VALUE'`` with single quotes around the value.
    """
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"export {k}='{v}'" for k, v in entries.items()]
    body = "\n".join(lines)
    generated_by = f"lyra setup {_time_str()}"
    env_path.write_text(
        _ENV_TEMPLATE.format(generator=generated_by, entries=body),
        encoding="utf-8",
    )


def _time_str() -> str:
    import time
    return time.strftime("%Y-%m-%dT%H:%M:%S")


@dataclass
class SettingsConfig:
    """User-facing settings persisted across sessions."""

    last_model: str = ""
    last_provider: str = ""
    fallback_chain: list[str] = field(default_factory=lambda: list(DEFAULT_FALLBACK_CHAIN))
    theme: str = "dracula"
    permission_mode: str = "allow"
    auto_detect_tasks: bool = True
    config_version: int = 2


def lyra_home() -> Path:
    """Resolve the directory that holds ``settings.json``."""
    env = os.environ.get("LYRA_HOME")
    if env:
        return Path(env).expanduser()
    return Path.home() / _DEFAULT_HOME_DIRNAME


def settings_path() -> Path:
    """Full path to settings.json (may not exist yet)."""
    return lyra_home() / _SETTINGS_FILENAME


def _atomic_write(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` via tempfile + rename."""
    parent = path.parent
    parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=".settings-", dir=str(parent))
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp_path, path)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass
        raise


def load_settings(path: Path | None = None) -> SettingsConfig:
    """Return settings from disk, filling in defaults for missing keys.

    When *path* is ``None`` the canonical ``~/.lyra/settings.json`` is used.
    Pass an explicit path to load project-local overrides (e.g.
    ``<repo>/.lyra/settings.json``).
    """
    if path is None:
        path = settings_path()
    if not path.is_file():
        return SettingsConfig()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return SettingsConfig()
    if not isinstance(data, dict):
        return SettingsConfig()
    return SettingsConfig(
        last_model=data.get("last_model", ""),
        last_provider=data.get("last_provider", ""),
        fallback_chain=data.get("fallback_chain", list(DEFAULT_FALLBACK_CHAIN)),
        theme=data.get("theme", "dracula"),
        permission_mode=data.get("permission_mode", "allow"),
        auto_detect_tasks=data.get("auto_detect_tasks", True),
        config_version=data.get("config_version", 2),
    )


def load_settings_dict(path: Path | str | None = None) -> dict[str, Any]:
    """Return settings as a raw dict, filling in defaults for missing keys.

    This is the variant that policy_loader and provider_registry use —
    they need ``.get("permissions")`` and ``.get("providers")``, not a
    structured ``SettingsConfig``.
    """
    if path is None:
        path = settings_path()
    if isinstance(path, str):
        path = Path(path)
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(data, dict):
        return {}
    return data


def save_settings(config: SettingsConfig) -> None:
    """Persist settings to ``~/.lyra/settings.json`` (atomic, 0600)."""
    data: dict[str, Any] = {
        "config_version": config.config_version,
        "last_model": config.last_model,
        "last_provider": config.last_provider,
        "fallback_chain": config.fallback_chain,
        "theme": config.theme,
        "permission_mode": config.permission_mode,
        "auto_detect_tasks": config.auto_detect_tasks,
    }
    path = settings_path()
    _atomic_write(path, json.dumps(data, indent=2, sort_keys=True))
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
