"""Persist Lyra settings to ``~/.lyra/settings.json``.

Settings are user preferences: last model, primary provider, theme,
permission mode, and task auto-detection. This is separate from
``auth.json`` which holds secrets. Both live in ``~/.lyra/`` with
mode-0600 enforced.

v6.0.0: Removed fallback_chain (deprecated). Use primary_provider instead.
"""

from __future__ import annotations

import json
import os
import stat
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "LYRA_CONFIG_VERSION",
    "SettingsConfig",
    "load_settings",
    "load_settings_dict",
    "save_settings",
    "settings_path",
    "write_env_file",
]

# DEPRECATED in v6.0.0: Use primary_provider instead
# Kept for backward compatibility during migration
_DEPRECATED_DEFAULT_FALLBACK_CHAIN = [
    "anthropic", "deepseek", "gemini", "openai",
    "bedrock", "kimi", "qwen", "ollama",
]

LYRA_CONFIG_VERSION = 4  # Bumped for v6.0.0 config schema change

_DEFAULT_HOME_DIRNAME = ".lyra"
_SETTINGS_FILENAME = "settings.json"

_ENV_TEMPLATE = """\
# Lyra environment — generated by {generator}.
# This file is safe to source in your shell profile.
{entries}
"""


def write_env_file(env_path: Path, entries: dict[str, str]) -> None:
    """Write a shell-compatible env file to ``env_path``.

    ``entries`` is a dict of key/value pairs; each is written as
    ``export KEY='VALUE'`` with single quotes around the value.
    """
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"export {k}='{v}'" for k, v in entries.items()]
    body = "\n".join(lines)
    generated_by = f"lyra setup {_time_str()}"
    env_path.write_text(
        _ENV_TEMPLATE.format(generator=generated_by, entries=body),
        encoding="utf-8",
    )


def _time_str() -> str:
    import time
    return time.strftime("%Y-%m-%dT%H:%M:%S")


@dataclass
class SettingsConfig:
    """User-facing settings persisted across sessions.

    v6.0.0: Replaced fallback_chain with primary_provider.
    Old configs with fallback_chain are automatically migrated.
    """

    last_model: str = ""
    last_provider: str = ""
    primary_provider: str = "auto"  # v6.0.0: Replaces fallback_chain
    enable_task_routing: bool = True  # v6.0.0: Enable smart model routing within provider
    theme: str = "dracula"
    permission_mode: str = "allow"
    auto_detect_tasks: bool = True
    config_version: int = 4  # v6.0.0: Bumped for schema change


def lyra_home() -> Path:
    """Resolve the directory that holds ``settings.json``."""
    env = os.environ.get("LYRA_HOME")
    if env:
        return Path(env).expanduser()
    return Path.home() / _DEFAULT_HOME_DIRNAME


def settings_path() -> Path:
    """Full path to settings.json (may not exist yet)."""
    return lyra_home() / _SETTINGS_FILENAME


def _atomic_write(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` via tempfile + rename."""
    parent = path.parent
    parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=".settings-", dir=str(parent))
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp_path, path)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass
        raise


def load_settings(path: Path | None = None) -> SettingsConfig:
    """Return settings from disk, filling in defaults for missing keys.

    When *path* is ``None`` the canonical ``~/.lyra/settings.json`` is used.
    Pass an explicit path to load project-local overrides (e.g.
    ``<repo>/.lyra/settings.json``).

    v6.0.0: Automatically migrates old configs with fallback_chain to
    primary_provider (uses first provider in chain).
    """
    if path is None:
        path = settings_path()
    if not path.is_file():
        return SettingsConfig()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return SettingsConfig()
    if not isinstance(data, dict):
        return SettingsConfig()

    # v6.0.0 migration: fallback_chain → primary_provider
    primary_provider = data.get("primary_provider", "auto")
    if "fallback_chain" in data and "primary_provider" not in data:
        # Migrate: use first provider from old chain
        fallback_chain = data.get("fallback_chain", [])
        if fallback_chain and isinstance(fallback_chain, list):
            primary_provider = fallback_chain[0]
            import logging
            logging.warning(
                "Config migration: fallback_chain is deprecated. "
                f"Using first provider '{primary_provider}' as primary_provider. "
                "Update your config with: lyra config set primary_provider %s",
                primary_provider
            )

    return SettingsConfig(
        last_model=data.get("last_model", ""),
        last_provider=data.get("last_provider", ""),
        primary_provider=primary_provider,
        enable_task_routing=data.get("enable_task_routing", True),
        theme=data.get("theme", "dracula"),
        permission_mode=data.get("permission_mode", "allow"),
        auto_detect_tasks=data.get("auto_detect_tasks", True),
        config_version=data.get("config_version", 4),
    )


def load_settings_dict(path: Path | str | None = None) -> dict[str, Any]:
    """Return settings as a raw dict, filling in defaults for missing keys.

    This is the variant that policy_loader and provider_registry use —
    they need ``.get("permissions")`` and ``.get("providers")``, not a
    structured ``SettingsConfig``.
    """
    if path is None:
        path = settings_path()
    if isinstance(path, str):
        path = Path(path)
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(data, dict):
        return {}
    return data


def save_settings(config: SettingsConfig) -> None:
    """Persist settings to ``~/.lyra/settings.json`` (atomic, 0600).

    v6.0.0: Saves primary_provider instead of fallback_chain.
    """
    data: dict[str, Any] = {
        "config_version": config.config_version,
        "last_model": config.last_model,
        "last_provider": config.last_provider,
        "primary_provider": config.primary_provider,
        "enable_task_routing": config.enable_task_routing,
        "theme": config.theme,
        "permission_mode": config.permission_mode,
        "auto_detect_tasks": config.auto_detect_tasks,
    }
    path = settings_path()
    _atomic_write(path, json.dumps(data, indent=2, sort_keys=True))
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
