"""``lyra daemon`` — REPL-free Eternal-Mode supervisor for the cron loop.

L4.0 — the cron loop becomes a free-standing process:
* The existing :class:`lyra_core.cron.CronDaemon` is the iteration body.
* :class:`harness_eternal.EternalLoop` wraps it with budget envelope,
  directive-file HITL, health endpoint, and circuit breaker.
* systemd / launchd units are generated by ``emit-units``.

L4.3 — budget envelope is enforced at the EternalLoop layer (no more
per-routine queue; over-budget pauses the loop and writes a directive
entry).

L4.4 — the ``/heartbeat`` endpoint is bound on ``127.0.0.1:9102`` by
default; supervisors poll it for liveness.

L4.1 (per-turn deadline + Restate workflow for ``AgentLoop``) and L4.2
(automatic context compaction) are *not* delivered by this CLI — they
require changes inside ``lyra-core/agent/loop.py`` and are tracked as
follow-up work. The current CLI ships the cron loop with full
durability, which is the highest-leverage piece for unattended
operation.

Usage
-----
::

    python -m lyra_cli.daemon_cmd run \
        --jobs ~/.lyra/cron/jobs.json \
        --runner my_module:run_routine

    python -m lyra_cli.daemon_cmd emit-units \
        --output-dir ./scripts
"""
from __future__ import annotations

import argparse
import asyncio
import importlib
import sys
from pathlib import Path
from typing import Any, Callable

from harness_eternal import (
    Budget,
    CircuitBreaker,
    EternalLoop,
    MemoryCap,
)
from harness_eternal.restate import LocalRuntime, step, workflow
from harness_eternal.supervisor import generate_units

from lyra_core.cron import CronDaemon, CronJob, CronStore


JobRunner = Callable[[CronJob], None]


def _log_only_runner(job: CronJob) -> None:
    """Default runner — logs to stderr and returns. Production deployments
    plug in a real runner via ``--runner module:fn``."""
    sys.stderr.write(f"[lyra-daemon] would run job {job.id} ({job.kind})\n")


def _load_runner(spec: str | None) -> JobRunner:
    if spec is None or not spec.strip():
        return _log_only_runner
    if ":" not in spec:
        raise ValueError(f"--runner expects 'module:attr' (got {spec!r})")
    module_name, attr = spec.split(":", 1)
    module = importlib.import_module(module_name)
    runner = getattr(module, attr)
    if not callable(runner):
        raise TypeError(f"runner {spec!r} is not callable")
    return runner


def _build_tick_workflow(cron_daemon: CronDaemon):
    """Wrap ``CronDaemon.tick()`` in a Restate workflow.

    Each tick is one journaled step. The cron daemon already isolates
    per-job exceptions (``daemon.py:84-92``), so a single bad job does
    not bring the tick down.
    """
    @workflow(name="lyra.cron_tick")
    async def lyra_tick(ctx) -> str:  # noqa: ANN001
        return await step(
            ctx,
            lambda: asyncio.to_thread(cron_daemon.tick),
            step_name="cron_tick",
        )

    return lyra_tick


def _cmd_run(args: argparse.Namespace) -> int:
    jobs_path = Path(args.jobs).expanduser().resolve()
    jobs_path.parent.mkdir(parents=True, exist_ok=True)
    state_dir = Path(args.state_dir).expanduser().resolve()
    state_dir.mkdir(parents=True, exist_ok=True)

    runner = _load_runner(args.runner)
    store = CronStore(jobs_path=jobs_path)

    def _runner_adapter(job: CronJob) -> Any:
        return runner(job)

    cron_daemon = CronDaemon(
        store=store,
        runner=_runner_adapter,
        tick_interval=args.tick_interval_s,
    )

    runtime = LocalRuntime(state_dir / "restate")
    breaker = CircuitBreaker(after=args.breaker_after)
    tick_wf = _build_tick_workflow(cron_daemon)

    loop = EternalLoop(
        name="lyra",
        state_dir=state_dir,
        workflow=tick_wf,
        runtime=runtime,
        breaker=breaker,
        budget=Budget(
            usd_per_day=args.usd_per_day,
            tokens_per_day=args.tokens_per_day,
        ),
        memory_cap=MemoryCap(),
        deadline_per_iter_s=args.deadline_per_iter_s,
        poll_interval_s=args.poll_interval_s,
        breaker_after=args.breaker_after,
        health_port=args.health_port,
        enable_health_endpoint=not args.no_health_endpoint,
    )
    iters = loop.run_forever(
        max_iterations=args.max_iterations if args.max_iterations > 0 else None
    )
    sys.stdout.write(f"lyra-daemon: ran {iters} iteration(s)\n")
    return 0


def _cmd_emit_units(args: argparse.Namespace) -> int:
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    state_dir = Path(args.state_dir).expanduser().resolve()

    exec_start = (
        f"{sys.executable} -m lyra_cli.daemon_cmd run "
        f"--jobs {args.jobs} "
        f"--state-dir {state_dir.as_posix()} "
        f"--usd-per-day {args.usd_per_day}"
    )
    sysd, plist = generate_units(
        name="lyra",
        exec_start=exec_start,
        working_directory=state_dir,
        description="Lyra cron daemon (Eternal Mode)",
    )
    (output_dir / "lyra-daemon.service").write_text(sysd)
    (output_dir / "com.lyra.daemon.plist").write_text(plist)
    sys.stdout.write(f"lyra-daemon: wrote unit files to {output_dir}\n")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="lyra-daemon",
        description="Lyra cron daemon (Eternal Mode)",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    run = sub.add_parser("run", help="run the cron daemon under Eternal Mode")
    run.add_argument(
        "--jobs",
        default=str(Path("~/.lyra/cron/jobs.json").expanduser()),
        help="cron jobs JSON path",
    )
    run.add_argument(
        "--state-dir",
        default=str(Path("~/.lyra/eternal").expanduser()),
        help="EternalLoop state directory",
    )
    run.add_argument(
        "--runner",
        default=None,
        help="job runner callable, 'module:attr' (default: log-only)",
    )
    run.add_argument("--tick-interval-s", type=float, default=1.0)
    run.add_argument("--usd-per-day", type=float, default=1.0)
    run.add_argument("--tokens-per-day", type=int, default=1_000_000)
    run.add_argument("--deadline-per-iter-s", type=int, default=60)
    run.add_argument("--poll-interval-s", type=float, default=1.0)
    run.add_argument("--breaker-after", type=int, default=5)
    run.add_argument("--health-port", type=int, default=9102)
    run.add_argument("--no-health-endpoint", action="store_true")
    run.add_argument(
        "--max-iterations",
        type=int,
        default=0,
        help="exit after N iterations (0 = run forever; for tests)",
    )
    run.set_defaults(func=_cmd_run)

    emit = sub.add_parser("emit-units", help="write systemd + launchd unit files")
    emit.add_argument(
        "--state-dir",
        default=str(Path("~/.lyra/eternal").expanduser()),
    )
    emit.add_argument(
        "--jobs",
        default=str(Path("~/.lyra/cron/jobs.json").expanduser()),
    )
    emit.add_argument("--output-dir", default="./scripts")
    emit.add_argument("--usd-per-day", type=float, default=1.0)
    emit.set_defaults(func=_cmd_emit_units)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
