"""
Policy data model and GateDecision enum for deterministic tool-call gating.

Provides the ``Policy`` dataclass (immutable, least-privilege permission set)
and the ``GateDecision`` enum (ALLOW, ALLOW_WITH_SANDBOX, ASK_USER, BLOCK).

Part of P2: Deterministic Tool-Call Gating (Breakthrough #3).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List


class GateDecision(str, Enum):
    """Disposition returned by ``ToolGate.validate()``.

    Four gating levels, ordered from most permissive to most restrictive:

    * ``ALLOW`` — Tool call proceeds normally.
    * ``ALLOW_WITH_SANDBOX`` — Tool call proceeds under sandboxed execution.
    * ``ASK_USER`` — Tool call requires interactive user approval.
    * ``BLOCK`` — Tool call is denied outright.
    """

    ALLOW = "allow"
    ALLOW_WITH_SANDBOX = "allow_with_sandbox"
    ASK_USER = "ask_user"
    BLOCK = "block"


@dataclass(frozen=True)
class Policy:
    """Immutable least-privilege policy for deterministic tool-call gating.

    Generated by ``ToolGate.generate_policy()`` (LLM-assisted) and enforced
    by ``ToolGate.validate()`` (pure deterministic logic, no LLM).

    Attributes:
        allowed_tools: List of tool names permitted for this task.
            Empty list means no tools are allowed (deny-by-default).
        allowed_paths: Glob patterns for file paths the task may read/write.
            ``["**"]`` means any path (within workspace).
        allowed_domains: Glob patterns for network domains the task may reach.
            ``["*"]`` means any domain.
        max_tokens_per_call: Maximum output tokens per tool invocation.
            ``0`` means no token limit.
        requires_approval_for: Tool names that require interactive user
            approval before execution.
    """

    allowed_tools: List[str] = field(default_factory=list)
    allowed_paths: List[str] = field(default_factory=lambda: ["**"])
    allowed_domains: List[str] = field(default_factory=lambda: ["*"])
    max_tokens_per_call: int = 0
    requires_approval_for: List[str] = field(default_factory=list)
