"""lyra_harness_core — shared harness primitives for agent systems.

Public API:
    - AgentLoop, LoopResult
    - LLMProvider, MockLLM, AnthropicLLM, get_default_llm
    - Message, ToolCall, ToolResult, StopReason
    - Tool, ToolRegistry, ToolError
    - PermissionMode, PermissionPolicy, PermissionDecision
    - Hook, HookRegistry, HookEvent, HookDecision
    - Memory, MemoryEntry
    - Tracer, Span
    - PureFunctionAgent, AgentDecision, SideEffectLog, TrajectoryReplay
      (per docs/202 §4, docs/211 §4 — pure-function pattern)
    - BudgetController, BudgetExhausted, TTCCurve, TTCPoint,
      ActiveParamAccount, ActiveParamReading
      (per docs/202 §3, docs/199 — eval discipline)
    - ChainOfNoteGate, DocVerdict, NoteVerdict, ScoredDoc
      (per docs/199 Phase 3 — quality gate)
"""
from __future__ import annotations

from .agi_integration import AGIAwareLoop, AGIState
from .auto_compaction import (
    AutoCompactor,
    CompactionCandidate,
    CompactionDecision,
    CompactionResult,
    CompactionStrategy,
    CompactionVerification,
    FillStatus,
    QualitySpotCheck,
    compute_fill_ratio,
)
from .code_execution import (
    BatchExecutor,
    BatchResult,
    BatchSpec,
    CodeBlock,
    parse_batch_from_json,
)
from .context_router import (
    ContextClassifier,
    ContextDecision,
    ContextRoute,
    ContextRouter,
    ContextSignal,
    RuleBasedContextClassifier,
)
from .constitution import (
    Constitution,
    ConstitutionRegistry,
    Principle,
)
from .continuous_learning import (
    ContinuousLearner,
    EditEvent,
    EditRecorder,
    HeuristicExtractor,
    LearnedPreference,
    LearningReport,
    PreferenceExtractor,
)
from .cost import (
    BillingPeriod,
    CostEntry,
    CostReport,
    CostThresholdAlert,
    CostTracker,
    PricingTable,
)
from .distributed import (
    Bus,
    Envelope,
    Handler,
    Subscription,
    topic_matches,
)
from .evals import (
    ActiveParamAccount,
    ActiveParamReading,
    BudgetController,
    BudgetExhausted,
    TTCCurve,
    TTCPoint,
)
from .filesystem_context import FilesystemContext, StoredItem
from .events import Event, EventBus, Subscription, get_event_bus, set_event_bus
from .forensic import (
    ReplayComparator,
    Trajectory,
    TrajectoryOutcome,
    TrajectorySimilarity,
)
from .gates import (
    ChainOfNoteGate,
    DocVerdict,
    FactClaim,
    KGFactGate,
    KGFactVerdict,
    KGSource,
    NoteVerdict,
    RetractionGate,
    RetractionIndex,
    RetractionRecord,
    RetractionVerdict,
    ScoredDoc,
    StaticKGSource,
    StaticRetractionIndex,
)
from .hooks import Hook, HookDecision, HookEvent, HookExecution, HookHealth, HookRegistry, HookStats, HookWatchdog
from .integrations import (
    AdaptedDocument,
    AdaptedEdge,
    AdaptedGraph,
    AdaptedNode,
    adapt_graph,
    verify_graph_protocol,
)
from .isolation import (
    ContextNamespace,
    IsolatedContext,
    NamespacePermission,
    PermissionGrant,
)
from .kv_cache import (
    AppendOnlyContext,
    CacheBreakpoint,
    CacheFriendlySerializer,
    cache_fingerprint,
    estimate_cache_savings,
    stable_system_prefix,
)
from .loop import AgentLoop, LoopResult
from .marketplace import (
    CuratorHost,
    InMemoryCuratorHost,
    InMemoryMarketplaceHost,
    InstallResult,
    MarketplaceHost,
    MCPServer,
    PromotedSkill,
    SubmitResult,
    TrajectoryRecord,
    TrustTier,
    TrustVerdict,
)
from .memory import Memory, MemoryEntry
from .memory_consolidation import (
    ConsolidationPolicy,
    ConsolidationReport,
    ExtractiveSummarizer,
    MemoryConsolidator,
    TagGrouping,
    TokenJaccardGrouping,
)
from .memory_store import (
    MemoryItem,
    MemoryKind,
    MemoryStore,
    RetrievalSpec,
    WorkingMemory,
)
from .messages import Message, StopReason, ToolCall, ToolResult
from .models import AnthropicLLM, LLMProvider, MockLLM, get_default_llm
from .providers import (
    AnthropicProvider,
    OpenAICompatibleProvider,
    ProviderConfig,
    ProviderHealth,
    ProviderInfo,
    ProviderKind,
    ProviderRegistry,
    StreamChunk,
    TokenUsage,
    create_provider,
    create_provider_registry,
    get_provider_registry,
)
from .multi_hop import (
    DecompositionCache,
    DecompositionEntry,
    HashEmbedder,
    HippoRAGRetriever,
    IRCoTOperator,
    IRCoTResult,
    PersonalizedPageRank,
    RetrievalResult,
    RetrievedDoc,
    SelfAskOperator,
    SelfAskResult,
    SimpleDocument,
    SimpleEdge,
    SimpleGraph,
    SimpleNode,
    StubLLM,
    StubRetriever,
    TitleEntityExtractor,
)
from .observability import Span, Tracer
from .plugins import (
    DependencySpec,
    HookBinding,
    PluginInstance,
    PluginLifecycle,
    PluginManifest,
    PluginSandbox,
    SandboxConfig,
    SandboxResult,
    SemVer,
    ToolDeclaration,
    check_version_constraint,
    load_manifest_from_yaml,
    parse_manifest,
    validate_domain,
    validate_path,
)
from .orchestration import (
    AgentDecision,
    PureFunctionAgent,
    SideEffectLog,
    SideEffectRecord,
    TrajectoryReplay,
    decision_fingerprint,
)
from .pages import (
    EditConflict,
    Page,
    PageEditor,
    PageHistory,
    PageSnapshot,
    line_diff_summary,
)
from .permissions import PermissionDecision, PermissionMode, PermissionPolicy
from .pipeline import MultiHopPipeline, PipelineResult, PipelineStep
from .programs import (
    BootstrapFewShot,
    Demonstration,
    Example,
    MultiHopProgram,
    ProgramOutput,
    Signature,
    evaluate,
)
from .provenance import (
    ProvenanceLedger,
    Witness,
    WitnessKind,
    WitnessLattice,
)
from .render import (
    eval_run_to_json,
    eval_run_to_markdown,
    structured_log_lines,
    trace_to_json,
    trace_to_markdown,
    witness_lattice_to_json,
    witness_lattice_to_markdown,
)
from .replay import (
    ReplayEvent,
    ReplayEventKind,
    Trace,
    TraceBuilder,
    TraceComparator,
    TraceDelta,
    TraceDeltaKind,
)
from .routines import (
    CronExpression,
    CronParseError,
    FireResult,
    Routine,
    RoutineFire,
    RoutineRegistry,
    TriggerKind,
)
from .routing import BELLERouter, QueryType, RouteDecision, RuleBasedClassifier
from .routing import EffortConfig, EffortDecision, EffortRouter, EffortTier, infer_effort
from .routing import AgentPhase, PhaseConfig, PhaseDecision, PhaseRouter, infer_phase
from .slash_commands import (
    CommandArgument as SlashCommandArgument,
    CommandConfig,
    CommandDefinition as SlashCommandDefinition,
    CommandFlag as SlashCommandFlag,
    SlashCommandRegistry,
    fuzzy_match,
    fuzzy_match_commands,
    load_commands_from_directories,
    load_commands_from_yaml,
)
from .skill_format import (
    SkillInput,
    SkillManifest,
    SkillManifestRegistry,
    SkillOutput,
    SkillRetry,
    SkillTrigger,
    SkillValidationResult,
    load_skill,
    load_skill_from_markdown,
    load_skill_from_yaml,
    validate_skill_manifest,
)
from .skill_auto import (
    PromotionVerdict,
    SkillCandidate,
    SkillExtractor,
    SkillPromoter,
)
from .skill_drift import (
    DriftAlert,
    DriftPolicy,
    SkillDriftMonitor,
    SkillInvocation,
)
from .teams import (
    AgentRole,
    AgentTeam,
    Mailbox,
    MailboxRouter,
    Task,
    TaskList,
    TaskStatus,
)
from .unified_memory_router import (
    BanditArm,
    CompressionPolicy as MemoryCompressionPolicy,
    FeatureExtractor as MemoryFeatureExtractor,
    MemoryFeatures,
    MemoryTier,
    MultiArmedBandit,
    RawMemory,
    RetentionPolicy as MemoryRetentionPolicy,
    StoreDecision,
    UnifiedMemoryRouter,
)
from .tool_masking import (
    MaskRule,
    ToolDescriptor,
    ToolMask,
    ToolMaskApplier,
    ToolMaskMode,
    ToolMaskPolicy,
    build_safety_policy,
    build_strict_policy,
)
from .tool_runtime import (
    ExponentialBackoff,
    NoRetry,
    RetryPolicy,
    ToolEngine,
    ToolExecution,
)
from .tools import Tool, ToolError, ToolRegistry
from .verifier import (
    AxisVerdict,
    CompositeVerdict,
    HITLVerifier,
    Severity,
    StubDiffVerifier,
    StubDryRunVerifier,
    StubPermissionVerifier,
    StubPolicyVerifier,
    Verifier,
    VerifierAxis,
    VerifierComposer,
)
from .workflow_integrity import (
    Attestation,
    AttestationVerdict,
    ChainVerification,
    TrustChain,
    WorkflowIntegrity,
    generate_key,
    hash_content,
    sign,
    verify,
)

__all__ = [
    "ActiveParamAccount",
    "BatchExecutor",
    "BatchResult",
    "BatchSpec",
    "CodeBlock",
    "parse_batch_from_json",
    "ContextClassifier",
    "ContextDecision",
    "ContextRoute",
    "ContextRouter",
    "ContextSignal",
    "RuleBasedContextClassifier",
    # Plugin Manifest + Sandboxing
    "check_version_constraint",
    "DependencySpec",
    "HookBinding",
    "load_manifest_from_yaml",
    "parse_manifest",
    "PluginInstance",
    "PluginLifecycle",
    "PluginManifest",
    "PluginSandbox",
    "SandboxConfig",
    "SandboxResult",
    "SemVer",
    "ToolDeclaration",
    "validate_domain",
    "validate_path",
    "AnthropicProvider",
    "ActiveParamReading",
    "AdaptedDocument",
    "AdaptedEdge",
    "AdaptedGraph",
    "AdaptedNode",
    "AgentDecision",
    "AgentLoop",
    "AgentRole",
    "AgentTeam",
    "AnthropicLLM",
    "AxisVerdict",
    "BELLERouter",
    "BootstrapFewShot",
    "build_safety_policy",
    "build_strict_policy",
    "BudgetController",
    "BudgetExhausted",
    "Bus",
    "ChainOfNoteGate",
    "CompositeVerdict",
    "ConsolidationPolicy",
    "ConsolidationReport",
    "Constitution",
    "ConstitutionRegistry",
    "ContinuousLearner",
    "ContextNamespace",
    "CronExpression",
    "CronParseError",
    "CuratorHost",
    "DecompositionCache",
    "DecompositionEntry",
    "Demonstration",
    "DocVerdict",
    "DriftAlert",
    "DriftPolicy",
    "EffortConfig",
    "EffortDecision",
    "EffortRouter",
    "EffortTier",
    "infer_effort",
    "AgentPhase",
    "infer_phase",
    "PhaseConfig",
    "PhaseDecision",
    "PhaseRouter",
    "DualUseClassifier",
    "DualUseGate",
    "DualUseVerdict",
    "EditConflict",
    "EditEvent",
    "EditRecorder",
    "Envelope",
    "Event",
    "EventBus",
    "get_event_bus",
    "set_event_bus",
    "Subscription",
    "Example",
    "ExtractiveSummarizer",
    "FilesystemContext",
    "FireResult",
    "GateAction",
    "GateDecision",
    "Handler",
    "HashEmbedder",
    "HeuristicExtractor",
    "BanditArm",
    "HITLVerifier",
    "HippoRAGRetriever",
    "IRCoTOperator",
    "IRCoTResult",
    "Hook",
    "HookDecision",
    "HookEvent",
    "HookExecution",
    "HookHealth",
    "HookRegistry",
    "HookStats",
    "HookWatchdog",
    "InMemoryCuratorHost",
    "InMemoryMarketplaceHost",
    "InstallResult",
    "IsolatedContext",
    "KeywordRiskClassifier",
    "LLMProvider",
    "LearnedPreference",
    "LearningReport",
    "LoopResult",
    "MCPServer",
    "Mailbox",
    "MailboxRouter",
    "MarketplaceHost",
    "MaskRule",
    "Memory",
    "MemoryCompressionPolicy",
    "MemoryConsolidator",
    "MemoryFeatureExtractor",
    "MemoryFeatures",
    "MemoryRetentionPolicy",
    "MemoryTier",
    "MultiArmedBandit",
    "MultiHopPipeline",
    "MultiHopProgram",
    "MemoryEntry",
    "Message",
    "MockLLM",
    "NamespacePermission",
    "NoteVerdict",
    "Page",
    "PageEditor",
    "PageHistory",
    "PageSnapshot",
    "PipelineResult",
    "PipelineStep",
    "ProgramOutput",
    "PermissionDecision",
    "PermissionGrant",
    "Principle",
    "PromotedSkill",
    "PermissionMode",
    "PermissionPolicy",
    "PersonalizedPageRank",
    "PreferenceExtractor",
    "PureFunctionAgent",
    "QueryType",
    "RawMemory",
    "ReplayComparator",
    "RiskLevel",
    "RetractionGate",
    "RetractionIndex",
    "RetractionRecord",
    "RetractionVerdict",
    "RetrievalResult",
    "RetrievedDoc",
    "RouteDecision",
    "RuleBasedClassifier",
    "ScoredDoc",
    "SelfAskOperator",
    "Severity",
    "Signature",
    "SkillCandidate",
    "SkillInput",
    "SkillManifest",
    "SkillManifestRegistry",
    "SkillOutput",
    "SkillRetry",
    "SkillTrigger",
    "SkillValidationResult",
    "SkillDriftMonitor",
    "SkillExtractor",
    "SkillInvocation",
    "SkillPromoter",
    "SelfAskResult",
    "SlashCommandArgument",
    "SlashCommandDefinition",
    "SlashCommandFlag",
    "SlashCommandRegistry",
    "CommandConfig",
    "fuzzy_match",
    "fuzzy_match_commands",
    "load_commands_from_directories",
    "load_commands_from_yaml",
    "load_skill",
    "load_skill_from_markdown",
    "load_skill_from_yaml",
    "SideEffectLog",
    "SideEffectRecord",
    "SimpleDocument",
    "SimpleEdge",
    "SimpleGraph",
    "SimpleNode",
    "Span",
    "StaticRetractionIndex",
    "StoreDecision",
    "StoredItem",
    "StubDiffVerifier",
    "StubDryRunVerifier",
    "StubPermissionVerifier",
    "StubPolicyVerifier",
    "SubmitResult",
    "StubLLM",
    "StubRetriever",
    "StopReason",
    "Subscription",
    "TTCCurve",
    "TTCPoint",
    "TagGrouping",
    "TokenJaccardGrouping",
    "TitleEntityExtractor",
    "Tool",
    "ToolCall",
    "ToolDescriptor",
    "ToolError",
    "ToolMask",
    "ToolMaskApplier",
    "ToolMaskMode",
    "ToolMaskPolicy",
    "ToolRegistry",
    "ToolResult",
    "Tracer",
    "Trajectory",
    "TrajectoryOutcome",
    "TrajectoryRecord",
    "TrajectoryReplay",
    "TrajectorySimilarity",
    "Task",
    "TaskList",
    "TaskStatus",
    "TriggerKind",
    "TrustTier",
    "TrustVerdict",
    "Verifier",
    "VerifierAxis",
    "VerifierComposer",
    "Witness",
    "WitnessKind",
    "WitnessLattice",
    "adapt_graph",
    "decision_fingerprint",
    "ExponentialBackoff",
    "NoRetry",
    "RetryPolicy",
    "ToolEngine",
    "ToolExecution",
    "eval_run_to_json",
    "eval_run_to_markdown",
    "evaluate",
    "get_default_llm",
    "line_diff_summary",
    "next_fire_after",
    "parse_cron",
    "structured_log_lines",
    "topic_matches",
    "trace_to_json",
    "trace_to_markdown",
    "validate_skill_manifest",
    "verify_graph_protocol",
    "witness_lattice_to_json",
    "witness_lattice_to_markdown",
    # Workflow integrity
    "Attestation",
    "AttestationVerdict",
    "ChainVerification",
    "TrustChain",
    "WorkflowIntegrity",
    "generate_key",
    "hash_content",
    "sign",
    "verify",
    # AGI integration
    "AGIAwareLoop",
    "AGIState",
    # Auto-compaction
    "AutoCompactor",
    "CompactionCandidate",
    "CompactionDecision",
    "CompactionResult",
    "CompactionStrategy",
    "CompactionVerification",
    "FillStatus",
    "QualitySpotCheck",
    "compute_fill_ratio",
    # KV-cache
    "AppendOnlyContext",
    "CacheBreakpoint",
    "CacheFriendlySerializer",
    "cache_fingerprint",
    "estimate_cache_savings",
    "stable_system_prefix",
]
