import type { Keybinding } from './types'

export const DEFAULT_KEYBINDINGS: Keybinding[] = [
  // ── Global ──────────────────────────────────────────────
  {
    id: 'global.openCommandPalette',
    combo: { key: 'p', ctrl: true },
    action: 'openCommandPalette',
    description: 'Open command palette',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.openTranscript',
    combo: { key: 'o', ctrl: true },
    action: 'openTranscript',
    description: 'Open transcript viewer',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.openHistorySearch',
    combo: { key: 'r', ctrl: true },
    action: 'openHistorySearch',
    description: 'Reverse history search',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.toggleTaskPanel',
    combo: { key: 't', ctrl: true },
    action: 'toggleTaskPanel',
    description: 'Toggle task panel',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.copyLastResponse',
    combo: { key: 'c', ctrl: true, shift: true },
    action: 'copyLastResponse',
    description: 'Copy last response to clipboard',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.openSideQuestion',
    combo: { key: 'b', ctrl: true, shift: true },
    action: 'openSideQuestion',
    description: 'Open side question',
    contexts: ['global', 'chat'],
  },
  {
    id: 'global.cyclePermissionMode',
    combo: { key: 'tab', shift: true },
    action: 'cyclePermissionMode',
    description: 'Cycle permission mode',
    contexts: ['global'],
  },
  {
    id: 'global.toggleVim',
    combo: { key: 'v', ctrl: true, alt: true },
    action: 'toggleVim',
    description: 'Toggle vim mode',
    contexts: ['global', 'chat'],
  },

  // ── Chat ────────────────────────────────────────────────
  {
    id: 'chat.submit',
    combo: { key: 'return' },
    action: 'submit',
    description: 'Submit input',
    contexts: ['chat'],
  },
  {
    id: 'chat.newline',
    combo: { key: 'return', shift: true },
    action: 'newline',
    description: 'Insert newline',
    contexts: ['chat', 'vimInsert'],
  },
  {
    id: 'chat.clearInput',
    combo: { key: 'c', ctrl: true },
    action: 'clearInput',
    description: 'Clear input (Ctrl+C)',
    contexts: ['chat', 'vimInsert'],
  },
  {
    id: 'chat.clearInputAlt',
    combo: { key: 'u', ctrl: true },
    action: 'clearInput',
    description: 'Clear input (Ctrl+U)',
    contexts: ['chat', 'vimInsert'],
  },
  {
    id: 'chat.navigateHistoryUp',
    combo: { key: 'upArrow' },
    action: 'navigateHistoryUp',
    description: 'Previous history entry',
    contexts: ['chat'],
  },
  {
    id: 'chat.navigateHistoryDown',
    combo: { key: 'downArrow' },
    action: 'navigateHistoryDown',
    description: 'Next history entry',
    contexts: ['chat'],
  },

  // ── Autocomplete ────────────────────────────────────────
  {
    id: 'autocomplete.next',
    combo: { key: 'downArrow' },
    action: 'autocompleteNext',
    description: 'Next suggestion',
    contexts: ['autocomplete'],
  },
  {
    id: 'autocomplete.prev',
    combo: { key: 'upArrow' },
    action: 'autocompletePrev',
    description: 'Previous suggestion',
    contexts: ['autocomplete'],
  },
  {
    id: 'autocomplete.accept',
    combo: { key: 'tab' },
    action: 'acceptSuggestion',
    description: 'Accept suggestion',
    contexts: ['autocomplete'],
  },
  {
    id: 'autocomplete.dismiss',
    combo: { key: 'escape' },
    action: 'dismissSuggestions',
    description: 'Dismiss suggestions',
    contexts: ['autocomplete'],
  },

  // ── Transcript ──────────────────────────────────────────
  {
    id: 'transcript.scrollUp',
    combo: { key: 'upArrow' },
    action: 'scrollUp',
    description: 'Scroll up',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.scrollDown',
    combo: { key: 'downArrow' },
    action: 'scrollDown',
    description: 'Scroll down',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.pageUp',
    combo: { key: 'pageup' },
    action: 'scrollPageUp',
    description: 'Page up',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.pageDown',
    combo: { key: 'pagedown' },
    action: 'scrollPageDown',
    description: 'Page down',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.scrollTop',
    combo: { key: 'home', ctrl: true },
    action: 'scrollTop',
    description: 'Scroll to top',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.scrollBottom',
    combo: { key: 'end', ctrl: true },
    action: 'scrollBottom',
    description: 'Scroll to bottom',
    contexts: ['transcript'],
  },
  {
    id: 'transcript.close',
    combo: { key: 'escape' },
    action: 'cancel',
    description: 'Close transcript',
    contexts: ['transcript'],
  },

  // ── Settings / Confirmation ─────────────────────────────
  {
    id: 'confirmation.confirm',
    combo: { key: 'y' },
    action: 'confirm',
    description: 'Confirm (yes)',
    contexts: ['confirmation'],
  },
  {
    id: 'confirmation.cancel',
    combo: { key: 'escape' },
    action: 'cancel',
    description: 'Cancel',
    contexts: ['confirmation', 'settings', 'modelPicker', 'releaseNotesPicker', 'commandPalette', 'rewindMenu', 'goalPanel', 'effortPicker', 'themePicker', 'pluginManager', 'hooksManager'],
  },

  // ── Vim Normal Mode ─────────────────────────────────────
  {
    id: 'vimNormal.enterInsertI',
    combo: { key: 'i' },
    action: 'vimEnterInsert',
    description: 'Enter insert mode',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.enterInsertA',
    combo: { key: 'a' },
    action: 'vimEnterInsertAfter',
    description: 'Enter insert mode (after cursor)',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.enterInsertO',
    combo: { key: 'o' },
    action: 'vimOpenBelow',
    description: 'Open line below and insert',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.enterInsertOUp',
    combo: { key: 'O' },
    action: 'vimOpenAbove',
    description: 'Open line above and insert',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.moveLeft',
    combo: { key: 'h' },
    action: 'vimMoveLeft',
    description: 'Move cursor left',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.moveDown',
    combo: { key: 'j' },
    action: 'vimMoveDown',
    description: 'Move cursor down',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.moveUp',
    combo: { key: 'k' },
    action: 'vimMoveUp',
    description: 'Move cursor up',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.moveRight',
    combo: { key: 'l' },
    action: 'vimMoveRight',
    description: 'Move cursor right',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.wordForward',
    combo: { key: 'w' },
    action: 'vimWordForward',
    description: 'Move to next word',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.wordBack',
    combo: { key: 'b' },
    action: 'vimWordBack',
    description: 'Move to previous word',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.deleteLine',
    combo: { key: 'd', ctrl: false },
    action: 'vimDeleteLine',
    description: 'Delete line (dd)',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.deleteChar',
    combo: { key: 'x' },
    action: 'vimDeleteChar',
    description: 'Delete character',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.undo',
    combo: { key: 'u' },
    action: 'vimUndo',
    description: 'Undo',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.lineStart',
    combo: { key: '0' },
    action: 'vimLineStart',
    description: 'Move to line start',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.lineEnd',
    combo: { key: '$' },
    action: 'vimLineEnd',
    description: 'Move to line end',
    contexts: ['vimNormal'],
  },
  {
    id: 'vimNormal.escape',
    combo: { key: 'escape' },
    action: 'vimEnterNormal',
    description: 'Enter normal mode',
    contexts: ['vimInsert'],
  },

  // ── Settings / Picker Navigation ────────────────────────
  {
    id: 'picker.navigateUp',
    combo: { key: 'upArrow' },
    action: 'navigateUp',
    description: 'Navigate up',
    contexts: ['settings', 'modelPicker', 'releaseNotesPicker', 'commandPalette', 'rewindMenu', 'goalPanel', 'effortPicker', 'themePicker'],
  },
  {
    id: 'picker.navigateDown',
    combo: { key: 'downArrow' },
    action: 'navigateDown',
    description: 'Navigate down',
    contexts: ['settings', 'modelPicker', 'releaseNotesPicker', 'commandPalette', 'rewindMenu', 'goalPanel', 'effortPicker', 'themePicker'],
  },
  {
    id: 'picker.select',
    combo: { key: 'return' },
    action: 'select',
    description: 'Select item',
    contexts: ['settings', 'modelPicker', 'releaseNotesPicker', 'commandPalette', 'rewindMenu', 'goalPanel', 'effortPicker', 'themePicker'],
  },
]
